# Generated by Django 5.2.8 on 2026-01-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
