# Generated by Django 5.2.8 on 2026-01-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_semester_end_date_semester_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='start_date',
        ),
    ]
