# Generated by Django 5.2.8 on 2026-01-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_remove_semester_end_date_remove_semester_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
