# Generated by Django 5.2.8 on 2026-01-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_faculty_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
