# Generated by Django 5.2.8 on 2026-01-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_faculty_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='status',
        ),
    ]
