# Generated by Django 5.2.8 on 2026-01-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_remove_faculty_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
