# Generated by Django 5.2.8 on 2026-01-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_department_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='batch',
            name='intake_year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='progression_year',
            field=models.DecimalField(decimal_places=1, default=1.1, max_digits=1),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='batch',
            name='year',
        ),
    ]
