# Generated by Django 5.2.8 on 2026-01-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_alter_batch_unique_together_batch_intake_year_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('course', 'intake_year')},
        ),
    ]
