# Generated by Django 5.2.8 on 2026-01-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_alter_batch_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='progression_year',
            field=models.DecimalField(decimal_places=1, default=1.1, max_digits=2),
        ),
    ]
