# Generated by Django 5.2.8 on 2026-02-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_alter_batch_progression_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.DecimalField(decimal_places=1, default=1.1, max_digits=2),
        ),
    ]
