# Generated by Django 5.2.8 on 2026-02-15 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0012_alter_semester_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hall_type', models.CharField(choices=[('LAB', 'Laboratory Hall'), ('LH', 'Lecture Hall'), ('SEMINAR', 'Seminar Room'), ('AUD', 'Auditorium'), ('CONF', 'Conference Hall')], default='LH', max_length=10)),
                ('capacity', models.IntegerField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.faculty')),
            ],
        ),
    ]
