# Generated by Django 5.2.8 on 2026-02-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0013_lecturehall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturehall',
            name='hall_type',
            field=models.CharField(choices=[('LAB', 'Laboratory'), ('LH', 'Lecture Hall'), ('SEMINAR', 'Seminar Room'), ('AUD', 'Auditorium'), ('CONF', 'Conference Hall')], default='LH', max_length=10),
        ),
    ]
