# Generated by Django 5.2.8 on 2026-02-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0016_alter_schedule_options_alter_schedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
    ]
