# Generated by Django 5.2.8 on 2026-02-24 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0017_alter_schedule_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('material_type', models.CharField(choices=[('pdf', 'PDF'), ('vid', 'Video'), ('link', 'Link'), ('doc', 'Document')], default='pdf', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='lecture_materials/')),
                ('external_url', models.URLField(blank=True, null=True)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.batchsubject')),
            ],
            options={
                'ordering': ['uploaded_on'],
            },
        ),
    ]
