# Generated by Django 5.2.8 on 2026-02-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0018_lecturematerials'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturematerials',
            name='file_detail',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
