# Generated by Django 5.2.8 on 2026-02-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0019_lecturematerials_file_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturematerials',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecturematerials',
            name='file_detail',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
