# Generated by Django 5.2.8 on 2026-01-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
