# Generated by Django 5.2.8 on 2026-01-06 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_announcement_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='description',
        ),
    ]
