# Generated by Django 5.2.8 on 2026-02-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_userannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userannouncement',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
