# Generated by Django 5.2.8 on 2026-02-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_recentactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentactivity',
            name='at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
