# Generated by Django 5.2.8 on 2026-02-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_recentactivity_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentactivity',
            name='target_content_info',
            field=models.JSONField(default={}, null=True),
        ),
    ]
