# Generated by Django 5.2.8 on 2026-02-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_recentactivity_target_content_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentactivity',
            name='target_content_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
