# Generated by Django 5.2.8 on 2026-01-15 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_initial'),
        ('university', '0009_alter_batch_unique_together_batch_intake_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.batch'),
        ),
    ]
