# Generated by Django 5.2.8 on 2026-01-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_student_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
